# Generated by Django 3.1.7 on 2021-04-01 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_readings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='readings',
            name='date',
            field=models.DateField(verbose_name='reading date'),
        ),
    ]
