# Generated by Django 3.1.7 on 2021-04-01 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_auto_20210401_1810'),
    ]

    operations = [
        migrations.RenameField(
            model_name='readings',
            old_name='time',
            new_name='reading',
        ),
    ]
