# Generated by Django 3.1.7 on 2021-04-01 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_auto_20210401_1814'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='readings',
            options={'ordering': ['-date']},
        ),
    ]
