# Generated by Django 3.1.7 on 2021-04-02 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0009_genre'),
    ]

    operations = [
        migrations.AddField(
            model_name='comic',
            name='genres',
            field=models.ManyToManyField(to='main_app.Genre'),
        ),
    ]
