# Generated by Django 3.1.7 on 2021-04-02 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0010_comic_genres'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reading',
            name='read',
            field=models.CharField(choices=[('M', 'Morning'), ('A', 'Afternoon'), ('N', 'Night')], default='M', max_length=1),
        ),
    ]
